# Generated by Django 3.1.6 on 2021-02-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shipping_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='shipping_address',
            new_name='state',
        ),
    ]
